### ISSUE TITLE
get_config not working under napalm==4.0.0 but works under 3.4.1

### ISSUE THREAD

**Issue by davama** [napalm-automation-community/napalm-s350#81]
### Environment
Python version ('python3 --version'): `Python 3.9.7`
* Napalm version ('pip show napalm') :  
```
Name: napalm
Version: 4.0.0
Summary: Network Automation and Programmability Abstraction Layer with Multivendor support
Home-page: https://github.com/napalm-automation/napalm
Author: David Barroso, Kirk Byers, Mircea Ulinic
Author-email: dbarrosop@dravetech.com, ping@mirceaulinic.net, ktbyers@twb-tech.com
License: Apache 2.0
Location: /home/user/dave-dev-environment/lib/python3.9/site-packages
Requires: cffi, future, jinja2, junos-eznc, lxml, ncclient, netaddr, netmiko, netutils, paramiko, pyeapi, pyYAML, requests, scp, setuptools, textfsm, ttp, ttp-templates, typing-extensions
Required-by: napalm-procurve, napalm-s350, napalm-sros, nornir-napalm
```
* Napalm-s350 version ('pip show napalm-s350': 
``` 
Name: napalm-s350
Version: 0.3.1
Summary: NAPALM driver for Cisco SMB switches (SF3xx, SF5xx, SG3xx, SG5xx)
Home-page: https://github.com/napalm-automation-community/napalm-s350
Author: Jasper Lievisse Adriaanse, Petr Klíma, Daniel Bacher
Author-email: j@jasper.la, qaxi@seznam.cz, mail@phill93.de
License: Apache 2.0
Location: /home/user/dave-dev-environment/lib/python3.9/site-packages
Requires: napalm, netaddr, netmiko
Required-by: 
```
* Cisco SMB switch model (for example 'SG500-28-K9' or 'SG350X-48P-K9': `SF302-08PP-K9`
* Napalm diagnostic output ('napalm --vendor s350 --user USER --debug HOSTNAME':
paste full output here
```
napalm --vendor s350 --user <user> --debug h-txa-2wdm-sw-1
Enter password: 
2022-08-16 11:03:40,152 - napalm - DEBUG - Starting napalm's debugging tool
2022-08-16 11:03:40,152 - napalm - DEBUG - Gathering napalm packages
2022-08-16 11:03:40,152 - napalm - DEBUG - napalm-aruba505==0.0.107
2022-08-16 11:03:40,153 - napalm - DEBUG - napalm-procurve==0.6.0
2022-08-16 11:03:40,153 - napalm - DEBUG - napalm-s350==0.3.1
2022-08-16 11:03:40,153 - napalm - DEBUG - napalm-sros==1.0.0
2022-08-16 11:03:40,153 - napalm - DEBUG - napalm==4.0.0
2022-08-16 11:03:40,153 - napalm - DEBUG - get_network_driver - Calling with args: ('s350',), {}
2022-08-16 11:03:40,156 - napalm - DEBUG - get_network_driver - Successful
2022-08-16 11:03:40,156 - napalm - DEBUG - __init__ - Calling with args: (<class 'napalm_s350.s350.S350Driver'>, 'h-txa-2wdm-sw-1', 'user'), {'password': '*******', 'timeout': 60, 'optional_args': {}}
2022-08-16 11:03:40,157 - napalm - DEBUG - __init__ - Successful
2022-08-16 11:03:40,157 - napalm - DEBUG - pre_connection_tests - Calling with args: (<napalm_s350.s350.S350Driver object at 0x7f5e9779b0d0>,), {}
2022-08-16 11:03:40,157 - napalm - DEBUG - open - Calling with args: (<napalm_s350.s350.S350Driver object at 0x7f5e9779b0d0>,), {}
2022-08-16 11:03:43,177 - napalm - DEBUG - open - Successful
2022-08-16 11:03:43,177 - napalm - DEBUG - connection_tests - Calling with args: (<napalm_s350.s350.S350Driver object at 0x7f5e9779b0d0>,), {}
2022-08-16 11:03:43,178 - napalm - DEBUG - get_facts - Calling with args: (<napalm_s350.s350.S350Driver object at 0x7f5e9779b0d0>,), {}
2022-08-16 11:03:45,897 - napalm - DEBUG - Gathered facts:
{
    "fqdn": "Unknown",
    "hostname": "H-TXA-2WDM-SW-1",
    "interface_list": [
        "FastEthernet1",
        "FastEthernet2",
        "FastEthernet3",
        "FastEthernet4",
        "FastEthernet5",
        "FastEthernet6",
        "FastEthernet7",
        "FastEthernet8",
        "GigabitEthernet1",
        "GigabitEthernet2",
        "Port-channel1",
        "Port-channel2",
        "Port-channel3",
        "Port-channel4",
        "Port-channel5",
        "Port-channel6",
        "Port-channel7",
        "Port-channel8"
    ],
    "model": "SF302-08PP-K9",
    "os_version": "1.3.7.18",
    "serial_number": "bla",
    "uptime": 3966907,
    "vendor": "Cisco"
}
{
    "fqdn": "Unknown",
    "hostname": "H-TXA-2WDM-SW-1",
    "interface_list": [
        "FastEthernet1",
        "FastEthernet2",
        "FastEthernet3",
        "FastEthernet4",
        "FastEthernet5",
        "FastEthernet6",
        "FastEthernet7",
        "FastEthernet8",
        "GigabitEthernet1",
        "GigabitEthernet2",
        "Port-channel1",
        "Port-channel2",
        "Port-channel3",
        "Port-channel4",
        "Port-channel5",
        "Port-channel6",
        "Port-channel7",
        "Port-channel8"
    ],
    "model": "SF302-08PP-K9",
    "os_version": "1.3.7.18",
    "serial_number": "bla",
    "uptime": 3966907,
    "vendor": "Cisco"
}
2022-08-16 11:03:45,897 - napalm - DEBUG - get_facts - Successful
2022-08-16 11:03:45,897 - napalm - DEBUG - close - Calling with args: (<napalm_s350.s350.S350Driver object at 0x7f5e9779b0d0>,), {}
2022-08-16 11:03:48,102 - napalm - DEBUG - close - Successful
2022-08-16 11:03:48,103 - napalm - DEBUG - post_connection_tests - Calling with args: (<napalm_s350.s350.S350Driver object at 0x7f5e9779b0d0>,), {}
```

### Steps to Reproduce
```
driver = get_network_driver("s350")
device = driver(device_name,'username','password')
device.open()
output = device.get_config()
``` 

### Expected Behavior
The `dict` output of the config.

### Observed Behavior
Under v3.4.1 (`pip install napalm==3.4.1`) I have no issues getting the output of `get_config` function.
WIth napalm==4.0.0 the following results:
```
Traceback (most recent call last):
  File "/home/user/dave-dev-environment/my-napalm-s350-test.py", line 34, in <module>
    output = device.get_config()
  File "/home/user/dave-dev-environment/lib64/python3.9/site-packages/napalm_s350/s350.py", line 209, in get_config
    startup = self._send_command("show startup-config")
  File "/home/user/dave-dev-environment/lib64/python3.9/site-packages/napalm_s350/s350.py", line 143, in _send_command
    output = self.device.send_command(command)
  File "/home/user/dave-dev-environment/lib64/python3.9/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/user/dave-dev-environment/lib64/python3.9/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: 'H\\-TXA\\-2WDM\\-SW\\-1\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

I can see in the netmiko debug log that it runs the commands as expected (`show startup-config`) but as the config is being spit out, I eventually get `Patter not detected` error
```
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: show
DEBUG:netmiko:read_channel:  startup-config
...
...
...
DEBUG:netmiko:read_channel: !

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: interface gigabitethernet2
 description H-TXA-2W-SW-1(A17)
 storm-control broadcast enable
 storm-control broadcast level kbps 3500
DEBUG:netmiko:read_channel: 
 storm-control include-multicast unknown-unicast
DEBUG:netmiko:read_channel: 

DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel:  switchport trunk allowed vlan add 63,224,663,824,1063,1224,2063
 switchport forbidden default-vlan

#### there is still just 10 more lines left for the whole config to finish, but it errors out here
```

Please let me know if need more information from me.
First time posting here.
Hope I did this right.

Thank you,
Dave

**Comment by davama** [comment]
Found the issue.
It was technically not napalm but netmiko.
With the latest netmiko version they added a `read_timeout=10.0` to the `_send_command` function under netmiko.base_connection.

i basically copied over the s350 napalm `_send_command` into custom_napalm.s350 (which replaces the original function) and added `read_timeout=20` to the netmiko call in `self.device._send_command(bla, read_timeout=20)`

**Comment by qaxi** [comment]
Sooo , what is conclusion.
Is the issue specific for your environment ?

**Comment by davama** [comment]
Well the default netmiko `read_timeout=10.0` setting is not specific, but my device taking more than 10 seconds to spit the config is.
